### PR TITLE
use php:7-fpm image and drop deprecated mysql php ext

### LINKED ISSUE #45: use php:7-fpm as base image?
Piwik [recommends PHP7](https://piwik.org/docs/requirements/#recommended-configuration), is there a good reason why the docker file is based on php:5.6-fpm?

### PR DESCRIPTION
**Pull request by juliencarnot**
fixes #45 . mysql php-ext is deprecated with php7 and one of the recommended replacements is pdo_mysql.

### CODE REVIEW

**Comment by bla-kw** [comment]
The current stable geoip-1.0.8 does not compile with PHP7.0. I had to change it to the current beta geoip-1.1.1 to build it:
`RUN pecl install APCu geoip-1.1.1`

**Comment by juliencarnot** [comment]
Sorry about that bla-kw, the container built with no errors and since I'm using GeoIP and PHP MaxMind API (not PECL), I didn't notice the issue.
@pierreozoux : what's your recommendation? Use this beta version (and risk to forget about it and not use next stable versions) or wait for the final 1.1.1 release to merge this pull request?

**Comment by pierreozoux** [comment]
Sorry for the delay.

Yes, I'd wait for final realease.

Thanks!

**Comment by cwildfoerster** [comment]
Any update?

**Comment by juliencarnot** [comment]
GeoIP 1.1.1 is [still in beta](https://pecl.php.net/package/geoip). Haven't had any issues using that beta version though...

**Comment by pierreozoux** [comment]
@juliencarnot still beta?

**Comment by juliencarnot** [comment]
It's still marked as beta but was released on 2016-08-19 and there hasn't been many issues reported since that. I'm still using it with no problems.

**Comment by pierreozoux** [comment]
Ok cool :) Could you modify the template in the root then, and run the update script?

Thanks!

**Comment by juliencarnot** [comment]
Hum, not sure I can: I have no write access to this repo or no rights on the docker hub, if that's what you mean...

**Comment by pierreozoux** [comment]
I mean to update this PR :)

**Comment by juliencarnot** [comment]
Sorry for my misunderstanding, hadn't noticed the change of structure in the tree. The PR should be good to go now!

**Comment by juliencarnot** [comment]
@pierreozoux do you need me to do something else about this pull request?

**Comment by insekticid** [comment]
go go go! we are waiting for this upgrade! since 7.1 has better performance

**Comment by pierreozoux** [comment]
I'm really sorry to be a blocker here... It is a big change, and I don't have enough time to test it :/

Hope somebody can jump in and help me/us!
PS, you can remove me as MAINTAINER as it is no longer mandatory field in docker. (And as actually, I don't maintain it much :/ )

**Comment by insekticid** [comment]
So how to deal with it? 
You should add @juliencarnot as maintainer?

I made local merge of this PR and it looks great, now I am building my custom image in my private registry and will test it very soon

**Comment by Silvenga** [comment]
Running the apache image now after I rebased onto master - https://github.com/silvenga-docker/docker-piwik. 

I haven't found any issues.

**Comment by insekticid** [comment]
here is my compact version (74MB) with speedy PHP 7.10 nginx on alpine linux and autoarchive
- https://github.com/insekticid/docker-piwik
- https://hub.docker.com/r/insekticid/docker-piwik/tags/

**Comment by almereyda** [comment]
I have pulled @Silvenga's fork and it works fine.

**Comment by hgezim** [comment]
Could someone fix the merge conflicts and get this going?!

**Comment by Silvenga** [comment]
I can re-create the pull request if needed, but who has permission to accept a pull request here?

**Comment by Silvenga** [comment]
@mattab I wouldn't mind helping the Matomo community - I run this Matomo image on my personal servers and in production for work. Don't know if I'm qualified though. ¯\\\_(ツ)\_/¯

**Comment by juliencarnot** [comment]
@hgezim I could resolve the conflicts but GeoIP 1.1.1 is [still in beta](https://pecl.php.net/package/geoip), which is why it wasn't merged, even though I've been using it with no issues for months. @pierreozoux  & @mattab  , would you feel comfortable merging it now?

PS: I'll be happy to contribute an occasional PR or help testing from time to time, but I don't feel qualified enough on docker and parts of the stack to act as maintainer of an official image.

**Comment by hgezim** [comment]
I tried to take in the changes from master but not sure how to build Dockerfile.template.

**Comment by crazy-max** [comment]
Hi everyone, I designed an image of Matomo that I think might help you. I worked hard on it because today I use this image in my company in a high availability environment (Docker Swarm), which I couldn't do at the moment with your image. This concerns in particular the assembly of a volume cluster. There is also the image size that is not optimized (191 MB). I base myself on an Alpine Linux and the final size is 52 MB. If you wish I could contribute here with what I have already done on my side by opening some PRs: https://github.com/crazy-max/docker-matomo

**Comment by mattab** [comment]
Thanks @crazy-max for your message. What would you say are the main differences and advantages/disadvantages of your project VS this one? 

Are there any features not available in your project that was/is available here?

If @Silvenga @juliencarnot @hgezim agree, maybe it would be worht looking at your project in more details and if it's better / the way go to, maybe switch to make it our official docker image. However we have no field knowledge about docker and best practises so it's hard for me/us to take such decision. Would be awesome if we could come to a decision together that makes the project alive again and thriving and always up to date.

**Comment by crazy-max** [comment]
@mattab Here are the notable differences that I can quote :

* Alpine Linux 3.7 with Nginx and PHP 7.1
* One volume (/data) with only config, user plugins and preferences (thanks to PIWIK_USER_PATH env var)
* Cron task to keep GeoLite updated
* GeoIP Nginx module as location provider
* Cron task to archive Matomo reports (more efficient)
* Plugins and config are kept across upgrades of this image
* SSMTP relay to send emails
* Can customize Matomo log level
* Sessions are kept in /data (if you work with multiple instances of Matomo in HA environment)

To preserve the plugins installed by the user, I had to use inotify which will automatically move the plugins to the /data directory. So they will not be removed during an update and with this principle it will work in a HA environment.

**Comment by crazy-max** [comment]
@Silvenga,

* Options are not required. What do you mean by opinionated setup?
* Yes i agree with you, i have the same issue on my Swarm cluster. I think we have two options :
  * One container for each process (php-fpm, nginx, cron)
  * Use prefixes for logging on supervisord through event listener

**Comment by mattab** [comment]
Thanks for the note @crazy-max  - one more question: Is there any feature currently supported by `matomo-org/docker-piwik` and that would not be supported by `crazymax/matomo` yet ? 

@pierreozoux What do you think about @crazy-max project and approach?

**Comment by pierreozoux** [comment]
@mattab same comments as @Silvenga

**Comment by mattab** [comment]
Thanks for the update! Considering I don't know anything about the Docker world, please excuse my ignorance. @pierreozoux @Silvenga Do you think it makes sense to offer the 2 projects at once under the official Matomo umbrella, since they seem to cater to different needs? Or would it be better to somehow move all the improvements from @Silvenga project into this one?

I'm trying to figure out whether we would be better off having 2 Docker images concurrently (and possibly help our users and community better), or have only one that would slowly get all the improvements from the other one?

**Comment by crazy-max** [comment]
@pierreozoux @Silvenga I have taken comments into account and made changes to this effect. I think [my image](https://github.com/crazy-max/docker-matomo#included) solved most of the issues and can be ready to be an official image.

I have talked to @mattab about this and few things needs to be done :

* 1 Create an apache alternative
* 2 Only expose php-fpm and let's the final user choose fcgi server (nginx, caddy) through compose

The only problem with point 2 is that the user has to manage his own web server. We could therefore provide, as you suggested, examples of configuration for nginx, caddy, etc....
There is a lot of discussion about running multiple processes on a Docker image. Moreover Docker [indicates solutions to execute several services](https://docs.docker.com/config/containers/multi-service_container/) with for example Supervisord (which I put in the image). But log parsing can be painful with Supervisord.

I have put some examples through compose in my repository and I plan to add swarm and kubernetes.

If you are interested I can contribute and PR these features made on my repo.

**Comment by mattab** [comment]
Thanks for continuing the discussion both. 

From the comments, it seems that maybe the best ultimate solution is to have only one project, that would ideally meet everyone's needs by providing a small default image and allowing people to pick and choose the blocks. (eg. really like the idea of letting users choose apache VS nginx if possible). 

If you are both on board and happy to collaborate and merge all features into one project, then it sounds like the ideal solution and possible outcome. :tada:  

 @crazy-max  you suggested to create PRs on this repo, thanks for this! as this project is already the official one, it would make things easier probably and maybe help keep backward compatibility for existing users.
Once you have included all your improvements here, do you think you would be able to use this project in your own production environment?

**Comment by Silvenga** [comment]
Sorry, been busy as of late.

* I think the community would benefit from having multiple base images (e.g. based on Alpine, based on Debian, etc.) for each of the support image variants (Apache vs FPM). At the very least, keeping the Debian image around for the sake of existing images.
* Adding to the above point, using the official Alpine PHP image as a base with the extra modules installed as needed would reduce future maintenance requirements if the community wants an Alpine image.
* I also agree with @pierreozoux. Perhaps a full-stack solution is outside the scope of this official image. Rather, the official image documentation can point to fuller, more complete solutions if needed (like @crazy-max's).

**Comment by pierreozoux** [comment]
Thanks everybody for the input.
Supervisor is not an option for an official image except if you have a really good reason for that (we don't).

Nextcloud official docker image is the perfect example to follow! Everything is there:
 - example folder
 - alpine/debian apache/fpm base images
 - automation script for everything
 - apache as the sane default for beginer experience

To continue on that, I'd advise to add @Silvenga and @crazy-max to the contributors, and everybody do PR, and you just need one approval from a maintainer to get merged.
I'll setup that.

I prefer to be on the believer side that people do good PR, (and it is always easy to revert) rather than being the bottleneck and everybody is frustrated.

**Pull request merged**
